#!/bin/bash

py=$(which python3.9 python3.8 python3.7 | head -n 1)

scr=$(realpath $0)
pdir=$(dirname $scr)

[[ -z $py ]] && errExit "No supported python on the PATH"

PYTHONPATH=${pdir} $py ${pdir}/select-line.py "$@"
